paths:
  /api/tasks:
    get:
      tags:
        - tasks
      parameters:
        - name: token
          in: header
          description: 유저 토큰
          required: true
          schema:
            type: string
      summary: task 목록 조회
      description: task 목록 조회
      produces:
        - application/json
      responses:
        200:
          description: Successed get task list
        404:
          description: Not found task
        500:
          description: Server Internal Error
    post:
      tags:
        - tasks
      parameters:
        - name: token
          in: header
          description: 유저 토큰
          required: true
          schema:
            type: string
        - name: id
          in: params
          description: task ObjectID
          required: true
          schema:
            type: string
        - name: title
          in: body
          description: task 제목
          required: false
          schema:
            type: string
        - name: coordinates
          in: body
          description: task [위도, 경도]
          required: true
          schema:
            type: array
            items:
              type: Number
        - name: address
          in: body
          description: task 주소
          required: true
          schema:
            type: string
        - name: tag
          in: body
          description: 태그 ObjectID
          required: false
          schema:
            type: string
        - name: iconURL
          in: body
          description: task Icon 경로
          required: false
          schema:
            type: string
        - name: isFinished
          in: body
          description: task 수행 여부
          required: true
          schema:
            type: boolean
        - name: isCheckedArrive
          in: body
          description: 도착할 때 알림 여부
          required: true
          schema:
            type: boolean
        - name: isCheckedLeave
          in: body
          description: 떠날 때 알림 여부
          required: true
          schema:
            type: boolean
        - name: isCheckedDueDate
          in: body
          description: 마감기한 on/off 여부
          required: true
          schema:
            type: boolean
        - name: arriveMessage
          in: body
          description: 도착할 때 메세지
          required: true
          schema:
            type: string
        - name: leaveMessage
          in: body
          description: 떠날 때 메세지
          required: true
          schema:
            type: string
        - name: createdDate
          in: body
          description: task 생성 날짜
          required: true
          schema:
            type: string
        - name: dueDate
          in: body
          description: task 달성 기한
          required: false
          schema:
            type: string
      summary: task 작성
      description: task 작성
      produces:
        - application/json
      responses:
        200:
          description: Successful Operation
        400:
          description: Bad Request 혹은 Invalid request body
        500:
          description: Server Error

  /api/tasks/all:
    delete:
      tags:
        - tasks
      parameters:
        - name: user token
          in: Header Authorization
          description: 유저 token
          required: true
          schema:
            type: string
      summary: tag delete API
      description: token에 일치하는 유저의 태스크 모두 삭제
      produces:
        - application/json
      responses:
        204:
          description: Successed delete all task
        401:
          description: Invalid token
        404:
          description: Not found tag
        500:
          description: Server Internal Error

  /api/tasks/{taskId}:
    get:
      tags:
        - tasks
      parameters:
        - name: token
          in: header
          description: 유저 토큰
          required: true
          schema:
            type: string
        - name: id
          in: params
          description: task ID
          required: true
          schema:
            type: string
      summary: 특정 task 조회
      description: 특정 task 조회
      produces:
        - application/json
      responses:
        200:
          description: Successed get task
        400:
          description: Bad Request 혹은 Invalid request body
        500:
          description: Server Internal Error
    patch:
      tags:
        - tasks
      parameters:
        - name: token
          in: header
          description: 유저 토큰
          required: true
          schema:
            type: string
        - name: id
          in: params
          description: task ObjectID
          required: true
          schema:
            type: string
        - name: title
          in: body
          description: task 제목
          required: false
          schema:
            type: string
        - name: coordinates
          in: body
          description: task [위도, 경도]
          required: true
          schema:
            type: array
            items:
              type: Number
        - name: address
          in: body
          description: task 주소
          required: true
          schema:
            type: string
        - name: tag
          in: body
          description: 태그 ObjectID
          required: false
          schema:
            type: string
        - name: iconURL
          in: body
          description: task Icon 경로
          required: false
          schema:
            type: string
        - name: isFinished
          in: body
          description: task 수행 여부
          required: true
          schema:
            type: boolean
        - name: isCheckedArrive
          in: body
          description: 도착할 때 알림 여부
          required: true
          schema:
            type: boolean
        - name: isCheckedLeave
          in: body
          description: 떠날 때 알림 여부
          required: true
          schema:
            type: boolean
        - name: isCheckedDueDate
          in: body
          description: 마감기한 on/off 여부
          required: true
          schema:
            type: boolean
        - name: arriveMessage
          in: body
          description: 도착할 때 메세지
          required: true
          schema:
            type: string
        - name: leaveMessage
          in: body
          description: 떠날 때 메세지
          required: true
          schema:
            type: string
        - name: createdDate
          in: body
          description: task 생성 날짜
          required: true
          schema:
            type: string
        - name: dueDate
          in: body
          description: task 달성 기한
          required: false
          schema:
            type: string
      summary: 특정 task 수정
      description: 특정 task 수정
      produces:
        - application/json
      responses:
        204:
          description: Success
        404:
          description: Not found task
        500:
          description: Server Internal Error
    delete:
      tags:
        - tasks
      parameters:
        - name: token
          in: header
          description: 유저 토큰
          required: true
          schema:
            type: string
        - name: id
          in: params
          description: task ObjectID
          required: true
          schema:
            type: string
      summary: 특정 task 삭제
      description: 특정 task 삭제
      produces:
        - application/json
      responses:
        204:
          description: Successed remove task
        404:
          description: Not found task
        500:
          description: Server Internal Error
